"use client";
import { useActionState, useEffect, useRef } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { deleteTagAction, saveTagAction } from "@/app/actions/tags";
import { initialActionState } from "@/lib/action-state";
import { colorClass, TAG_COLORS } from "@/lib/tags";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
type Tag = { id: string; name: string; color: string };
function TagRow({ tag }: { tag: Tag }) { const [state, action, pending] = useActionState(saveTagAction, initialActionState); return <li className="p-4"><form action={action} className="flex flex-wrap items-end gap-3"><input type="hidden" name="id" value={tag.id} /><div className="min-w-40 flex-1 space-y-1"><Label>タグ名</Label><Input name="name" defaultValue={tag.name} maxLength={20} /></div><div className="w-32 space-y-1"><Label>色</Label><NativeSelect name="color" defaultValue={tag.color}>{TAG_COLORS.map((color) => <option key={color} value={color}>{color}</option>)}</NativeSelect></div><Button variant="outline" size="sm" disabled={pending}><Save className="size-4" />更新</Button></form><div className="mt-3 flex items-center justify-between"><span className={`rounded-full border px-2.5 py-1 text-xs ${colorClass(tag.color)}`}>#{tag.name}</span><form action={deleteTagAction}><input type="hidden" name="id" value={tag.id} /><Button variant="ghost" size="sm" className="text-destructive"><Trash2 className="size-4" />削除</Button></form></div>{state.message && <p role="status" className={`mt-2 text-sm ${state.ok ? "text-primary" : "text-destructive"}`}>{state.message}</p>}</li>; }
export function TagManager({ tags }: { tags: Tag[] }) { const [state, action, pending] = useActionState(saveTagAction, initialActionState); const ref=useRef<HTMLFormElement>(null); useEffect(()=>{if(state.ok) ref.current?.reset()},[state]); return <div className="space-y-6"><form ref={ref} action={action} className="grid items-end gap-4 rounded-xl border p-4 sm:grid-cols-[1fr_160px_auto]"><div className="space-y-2"><Label htmlFor="tag-name">タグ名</Label><Input id="tag-name" name="name" placeholder="例: 旅行" maxLength={20} required /></div><div className="space-y-2"><Label htmlFor="tag-color">色</Label><NativeSelect id="tag-color" name="color" defaultValue="blue">{TAG_COLORS.map((color)=><option key={color} value={color}>{color}</option>)}</NativeSelect></div><Button disabled={pending}><Plus className="size-4" />追加</Button>{state.message && <p role="status" className={`sm:col-span-3 text-sm ${state.ok ? "text-primary" : "text-destructive"}`}>{state.message}</p>}</form>{tags.length ? <ul className="divide-y rounded-xl border">{tags.map((tag)=><TagRow key={tag.id} tag={tag}/>)}</ul> : <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">タグはまだありません。</p>}</div>; }
